// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-ui/lib/button')['default']
    ElCheckbox: typeof import('element-ui/lib/checkbox')['default']
    ElDivider: typeof import('element-ui/lib/divider')['default']
    ElHeader: typeof import('element-ui/lib/header')['default']
    ElInput: typeof import('element-ui/lib/input')['default']
    ElMain: typeof import('element-ui/lib/main')['default']
    ElMenu: typeof import('element-ui/lib/menu')['default']
    ElMenuItem: typeof import('element-ui/lib/menu-item')['default']
    ElPopconfirm: typeof import('element-ui/lib/popconfirm')['default']
    ElTable: typeof import('element-ui/lib/table')['default']
    ElTableColumn: typeof import('element-ui/lib/table-column')['default']
    IButton: typeof import('view-design/src/components/button')['default']
    IDivider: typeof import('view-design/src/components/divider')['default']
    IForm: typeof import('view-design/src/components/form')['default']
    IFormItem: typeof import('view-design/src/components/form-item')['default']
    IInput: typeof import('view-design/src/components/input')['default']
    ISlider: typeof import('view-design/src/components/slider')['default']
    ITable: typeof import('view-design/src/components/table')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Undefined: typeof import('./src/views/index.vue')['default']
  }
}

export {}
